App/DevForest/DevForest/Models/ThemeHelper.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using DeveloperForest.BLL;
using DevForest.Models;

namespace DevForest.Models
{
    public class ThemeHelper
    {
        Theme objBLL = new Theme();
        public int InsertTheme(ThemeModel model, string ImageName)
        {
            DeveloperForest.Model.ThemeModel obj = new DeveloperForest.Model.ThemeModel();
            obj.ThemeId = model.ThemeId;
            obj.CategoryId = model.CategoryId;
            obj.SubCategoryId = model.SubCategoryId;
            obj.Title = model.Title;
            obj.Description = model.Description;
            obj.Downloadlink = model.Downloadlink;
            obj.DemoLink = model.DemoLink;
            obj.CreatedBy = model.UserID;
            obj.ModifiedBy = model.UserID;
            obj.ImageName = ImageName;
            obj.RelatedLink1 = model.RelatedLink1;
            obj.RelatedLink2 = model.RelatedLink2;
            obj.RelatedLink3 = model.RelatedLink3;
            obj.RelatedLink4 = model.RelatedLink4;
            obj.RelatedLink5 = model.RelatedLink5;
            return objBLL.InsertTheme(obj);
        }

        public List<DeveloperForest.Model.ThemeModel> GetThemes()
        {

            List<DeveloperForest.Model.ThemeModel> ob = objBLL.GetThemes();
            return ob;
        }
        public DeveloperForest.Model.ThemeModel GetThemes(int ThemeId)
        {
            DeveloperForest.Model.ThemeModel ob = objBLL.GetThemes().Where(x => x.ThemeId == ThemeId).FirstOrDefault();
            return ob;
        }
        public string DeleteThemeById(int id)
        {
            return objBLL.DeleteThemeById(id);
        }
    }
}

App/DevForest/DevForest/Controllers/ThemeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DevForest.Models;
using System.IO;
namespace DevForest.Controllers
{
    public class ThemeController : Controller
    {
        ThemeHelper obj = new ThemeHelper();
        //
        // GET: /Theme/
        public ActionResult Theme()
        {
            CategoryHelper obj = new CategoryHelper();
            ThemeModel ob = new ThemeModel();
            ob.CategoryList = new SelectList(obj.GetCategories(), "CategoryId", "CategoryName");
            return View(ob);
        }
        [HttpPost]
        public ActionResult GetSubCategories(int id)
        {
            CategoryHelper obj = new CategoryHelper();
            var subCategory = obj.GetSubCategories().Where(x => x.CategoryId == id).ToList();
            return Json(subCategory, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        [AllowAnonymous]
        public ActionResult InsertTheme(ThemeModel model)
        {
            string fileName = "";
            if (string.IsNullOrEmpty(model.PreImageName))
            {
                Guid g = Guid.NewGuid();
                 fileName = g.ToString() + ".jpg";
            }
            else
            fileName = model.PreImageName;

            var image = Path.Combine(Server.MapPath("~/Upload/"), fileName);
            model.ImageName.SaveAs(image);
            var ThumbnailImage = Path.Combine(Server.MapPath("~/Upload/Thumbnail/"), fileName);
            model.ImageName.SaveAs(ThumbnailImage);
            obj.InsertTheme(model, fileName);
            return RedirectToAction("ThemeList");
        }

        public ActionResult ThemeList()
        {
            return View();
        }
        public JsonResult GetThemes(string order, int limit = 0, int offset = 0, string search = null, string sort = null)
        {
            try
            {
                ThemeHelper obj = new ThemeHelper();
                int count = 0;
                var Main = obj.GetThemes();
                if (!string.IsNullOrWhiteSpace(search))
                {

                    List<DeveloperForest.Model.ThemeModel> li = Main.Where(x => x.CategoryName.ToUpper().Contains(search.ToUpper())).ToList();
                    count = li.Count;
                    li = li.OrderBy(s => s.CategoryName).Skip(offset).Take(limit == 0 ? count : limit).ToList();
                    return Json(new { rows = li });
                }
                else
                {
                    count = Main.Count;
                    List<DeveloperForest.Model.ThemeModel> li = Main;
                    List<DeveloperForest.Model.ThemeModel> li2 = new List<DeveloperForest.Model.ThemeModel>();
                    if (sort != null)
                    {
                        var param = sort;
                        var propertyInfo = typeof(DeveloperForest.Model.ThemeModel).GetProperty(param);

                        if (order == "asc")
                        {
                            li2 = li.OrderBy(x => propertyInfo.GetValue(x, null)).Skip(offset).Take(limit == 0 ? count : limit).ToList();
                        }
                        else
                        {
                            li2 = li.OrderByDescending(x => propertyInfo.GetValue(x, null)).Skip(offset).Take(limit == 0 ? count : limit).ToList();
                        }
                    }
                    else
                    {
                        li2 = li.OrderBy(x => x.ThemeId).Skip(offset).Take(limit == 0 ? count : limit).ToList();
                    }

                    return Json(new { total = count, rows = li2 });
                }
            }
            catch (Exception ex)
            {
                return Json(new { Result = "ERROR", Message = ex.Message });
            }
        }

        public JsonResult GetThemeById(int ThemeId)
        {
            ThemeHelper obj = new ThemeHelper();
            return Json(obj.GetThemes(ThemeId), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult DeleteThemeByID(int ThemeId)
        {
            string res = obj.DeleteThemeById(ThemeId);
            string Imagepath = Server.MapPath("~/upload/" + res);
            string ThumbanailPath = Server.MapPath("~/upload/Thumbnail/" + res);
            if (System.IO.File.Exists(Imagepath))
            {
                System.IO.File.Delete(Imagepath);
            }
            if (System.IO.File.Exists(ThumbanailPath))
            {
                System.IO.File.Delete(ThumbanailPath);
            }
            return Json(1, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult UpdateThemeTrends(bool IsTrend,int ThemeID)
        {
            DeveloperForest.BLL.Category obj = new DeveloperForest.BLL.Category();

            obj.UpdateThemeTrends(IsTrend,ThemeID);

            return Json(true, JsonRequestBehavior.AllowGet);
        }
    }
}

App/DevForest/DevForest/Views/Theme/ThemeList.cshtml
@{
    ViewBag.Title = "ThemeList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Scripts.Render("~/bundles/jquery")
<style>
    .field-validation-error {
        margin-top: 4px;
        padding: 0;
    }

        .field-validation-error span {
            padding: 0;
            list-style: none;
            color: #cc0000;
        }

    .input-validation-error {
        border-color: #c00 !important;
    }
</style>

<div class="pageheader">
    <h2><i class="fa fa-home"></i> Input Fields <span>Subtitle goes here...</span></h2>
    <div class="breadcrumb-wrapper">
        <span class="label">You are here:</span>
        <ol class="breadcrumb">
            <li><a href="#">Bracket</a></li>
            <li class="active">Input Fields</li>
        </ol>
    </div>
</div>

<div class="contentpanel">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-dark">
                <div class="panel-heading">
                    <div class="panel-btns">
                        <a class="panel-close" href="">×</a>
                        <a class="minimize" href="">−</a>
                    </div><!-- panel-btns -->
                    <h3 class="panel-title">Theme List</h3>
                </div>

                <div id="divResponse" class="alert alert-dismissable hidden">
                    <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                    <span></span>
                </div>

                <div class="panel-body table-responsive">
                    <table id="bsTable" data-toggle="table"
                           data-toolbar="#toolbar"
                           class="table table-hover table-striped"
                           data-search="true"
                           data-show-toggle="true"
                           data-show-pagination-switch="true"
                           data-pagination="true"
                           data-page-size="10"
                           data-page-list="[25, 50, 100, All]"
                           data-side-pagination="server"
                           data-smart-display="true"
                           data-search-time-out="800"
                           data-show-columns="true"
                           data-method="post"
                           data-url="@Url.Action("GetThemes", "Theme")"
                           data-content-type="application/json"
                           data-data-type="json"
                           data-response-handler="responseHandler"
                           data-id-field="ThemeId"
                           data-show-export="true">
                        <thead>
                            <tr>
                                <th data-field="Title" data-sortable="true">Title</th>
                                <th data-field="CategoryName" data-sortable="true">Category</th>
                                <th data-field="SubCategoryName" data-sortable="true">SubCategory</th>
                                <th data-field="operate" data-formatter="ActionFormatter" data-events="operateEvents">IsTrending</th>
                                <th data-field="operate" data-formatter="operateFormatter" data-events="operateEvents">Action(s)</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function updatetrend(ctrl, idx) {
        var IsTrend = false;
        if ($(ctrl).is(':checked')) {
            IsTrend = true;
        }
        $.ajax({
            cache: false,
            type: "POST",
            url: '@Url.Action("UpdateThemeTrends", "Theme")',
            data: { IsTrend: IsTrend, ThemeID: idx },
            success: function (data) {
            },
            error: function (xhr, ajaxOptions, thrownError) {
                alert('Failed to retrieve books.');
            }
        });
    }
    function responseHandler(res) {
        return res;
    }
    function ActionFormatter(value, row, index) {
        return [
            '<input  name="IsTrend" class="IsTrend" onchange=updatetrend(this,'+row.ThemeId+') data-id=' + row.ThemeId +' type="checkbox">'
        ].join('');
    }
    function operateFormatter(value, row, index) {
        //alert(JSON.stringify(row));
       // console.log(JSON.stringify(row));

        return [
            '<a class="like btn btn-primary btn-xs" href="Theme?id=' + row.ThemeId + '" title="Edit">',
            '<i class="fa fa-pencil"></i>',
            '</a>  ',
            '  <a class="remove  btn btn-danger btn-xs" href="javascript:void(0)"  title="Remove">',
            '<i class="glyphicon glyphicon-remove"></i>',
            '</a>'
        ].join('');
    }

    window.operateEvents = {
        'click .like': function (e, value, row, index) {
            $('#txtCategoryName').val(row.CategoryName);
            $('#CategoryId').val(row.CategoryId);
            //alert('You click like action, row: ' + JSON.stringify(row));
        },
        'click .remove': function (e, value, row, index) {
            var cc = confirm("Are you sure you want to delete?");
            if (cc) {

                $.post('@Url.Action("DeleteThemeByID", "Theme")', { ThemeId: row.ThemeId }, function (res) {
                    if (res == 1) {
                        $('#bsTable').bootstrapTable('refresh');
                        callMsg('alert-success', 'Theme has been deleted');
                    }
                }, 'json');
            }
        }
    };
    function callMsg(classname, msg) {
        $('#divResponse').toggleClass('hidden');
        $('#divResponse').addClass(classname);
        $('#divResponse span').html(msg);

        setTimeout(function () {
            $('#divResponse').toggleClass('hidden');
        }, 4000);
    }
</script>

<script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")"></script>
@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/BootstrapTable");
@Styles.Render("~/Content/BootstarpTableCSS");